### PR TITLE
Ubuntu/Debian build

### PR DESCRIPTION
**Pull request by ivaradi**
These changes enable the building of Ubuntu/Debian packages automatically.

### CODE REVIEW

**Comment by enoch85** [comment]
@ivaradi Maybe update the README with how to install this on Ubuntu? Is the first build done yet?

**Comment by ivaradi** [comment]
@enoch85 No, Travis is not enabled on the repo yet, and I do not have the necessary access rights to do so.

**Comment by enoch85** [comment]
@rullzer @MorrisJobke Could you guys please enable Travis on this repo?

**Comment by rullzer** [comment]
Let me think about that. Our travis is already very busy. And I prefer to have those jobs in drone to be honest (since we control that ourselfs). And I like to avoid having 4 different kind of CI runs on this repo.

**Comment by enoch85** [comment]
Would be of great help! @ivaradi already have a PPA for Ubuntu packages and have been maintaining the theming repo very well. Would be super awesome if you could make it happen @rullzer

**Comment by ivaradi** [comment]
@rullzer OK, I am willing to move the Debian build to Drone. Could I get access to the Nextcloud Drone server, or shall I setup my own?

**Comment by rullzer** [comment]
@ivaradi if you just edit the .drone.yml file and submit a PR it should already work :)

**Pull request merged**
