### PR TITLE
scary wording on big changes #216 (translations missing)

### PR DESCRIPTION
**Pull request by k1l1**
Changed wording in folder.cpp as well as translation files client_en.ts and client_de.ts. 
Others are still missing.

### CODE REVIEW

**Comment by k1l1** [comment]
ok, now I only have the changes in folder.cpp

**Comment by juliushaertl** [comment]
@rullzer @MorrisJobke We have no transifex setup for the client repo yet. I guess it makes sense to add it.

**Comment by k1l1** [comment]
@juliushaertl I tried, there is some anoying end of line character, or something like this. I tried to drop it.

**Comment by MorrisJobke** [comment]
> @rullzer @MorrisJobke We have no transifex setup for the client repo yet. I guess it makes sense to add it.

🙈 Let's add it.

**Comment by MorrisJobke** [comment]
> 🙈 Let's add it.

#262 - l10n files are already on transifex and can be adjusted there now.

**Comment by jancborchardt** [comment]
Wording sounds good! :)

@k1l1 can you remove the changes to `translations/client_de.ts` and also squash the commits into one? If you are unfamiliar with it, it might be easiest to simply do a fresh branch, copy the changes in there, and open a new pull request. :)

**Comment by k1l1** [comment]
I managed to revert the client_de.ts on git ;)
It can be merged now.

**Pull request merged**
