### PR TITLE
Remove table for e2e and add an e2eMangledName column

### LINKED ISSUE #156: Waiting client when using e2e
During testing e2e I experienced a lot of waiting / hanging client, so I forced this via restart the client.
I couldn't figure out why it is in "wait" state, but I am happy to help you debugging it.

### PR DESCRIPTION
**Pull request by dantti**
This tries to fix #156 but it seems a lot more work has to be done

### CODE REVIEW

**Comment by dantti** [comment]
@rullzer can you please take a look as well?

**Comment by tcanabrava** [comment]
@rullzer - please take a look at this as I'm currently unable to review

**Comment by rullzer** [comment]
I have it on my todo

**Comment by tcanabrava** [comment]
I found the time to review and it seems correct.

**Pull request merged**
