### PR TITLE
Put log files somewhere else #221 (name conflict)

### PR DESCRIPTION
**Pull request by k1l1**
I found a problem regarding my last pull request #253, already talked to @camilasan.

The problem is, if the user adds several folders with the same (local) name, the logfiles get merged.
I thought this is straightforward to fix, but the only function input _folderPath_ carrys not enough information to fix this.
So I had to lable the logfiles (I added the according folderPath into the beginning of the logfile).
**Downside is**: I have to read the files again, which is always open to manipulation and errors, but the worst outcome, if someone is changing the logs is that: **A: new logfile gets created even if there is an existing one. B: logfiles get merged.**

I used the following nameing scheme so far (add "_1"). Do you have any ideas to improve this?

**Example:**
syncing all 3 folders:

_/subfolder/Folder1
/subfolder2/Folder1
/subfolder3/Folder1_

results in ...
unbenannt

log files look like this now:
unbenan2nt

If you have a better solution/idea let me know ;)

### CODE REVIEW

**Comment by juliushaertl** [comment]
Could we somehow include the full path to the folder in there? Otherwise it is quite hard to find the correct log file if there are multiple folders with the same name.

**Comment by k1l1** [comment]
Good idea, only problem is for the first folder I dont know in advance if there is a conflict or not.
I Could do


    /subfolder1/folder1 -> folder1_sync.log
    /subfolder2/folder1 -> subfolder2_folder1_sync.log
    /subfolder3/folder1 -> subfolder3_folder1_sync.log

**Comment by juliushaertl** [comment]
> Good idea, only problem is for the first folder I dont know in advance if there is a conflict or not.

I would just use this schema in general, not only for conflicting ones, makes searching for logs files a log easier then.

**Comment by k1l1** [comment]
Yeah, but it is still the same issue.
sub/subfolder/folder1 -> subfolder_folder1_sync.log
sub1/subfolder/folder1-> **subfolder_folder1_sync.log**  
again conflict.

**Comment by juliushaertl** [comment]
Hm, that is true, we could also just use a hash, but that would not help anything when looking for the log files. Maybe @camilasan has another idea?

**Comment by camilasan** [comment]
Not really. I was also thinking about using the full path. Yet..I am just not sure if I understand what is the problem with
sub/subfolder/folder1 -> sub_subfolder_folder1_sync.log
sub1/subfolder/folder1-> sub1_subfolder_folder1_sync.log
?

**Comment by rullzer** [comment]
There is another issue if you have multiple accounts I think... so maybe the account should be in there as well?

**Comment by camilasan** [comment]
@pfiff45 @juliushaertl  @rullzer 
Couldn't we create the same folder structure just for the logs?
something like:
~/..../Nextcloud/user/folder/subfolder/sync.log
The main goal of this change was just to keep the synced folders clean of the logs so It should be fine to create extra folders somewhere else. Or?

**Comment by k1l1** [comment]
We could do that, but in my view this raises confusion even more, since there are a bunch of folders with nothing but one subfolder, with in the end one single file.
I dont really get it, why multiple accounts play a role since logs are named after local folders.

Max file name length is 255 characters on NTFS.
ext2, ext3, ext4, zfs: no pathname limits; 255 bytes filename limit.
Could be a problem.

Beside that I think this is also not convenient to read. Therefore I would suggest, sticking with this solution: 

if there is **no conflict** name it like this:
_sub/subfolder1/folder1 -> folder1_sync.log_

if there is a **conflict with second folder**, specify the subdirectory
_sub/subfolder2/folder1 -> subfolder2_folder1_sync.log_

if there is a **conflict with second folder**, specify the subdirectory
_sub/subfolder3/folder1 -> subfolder3_folder1_sync.log_

unlikely case that there is a **conflict with the one subfolder above** rename to
sub2/subfolder3/folder1 -> sub_subfolder3_folder1_sync.log

and so on.

**Comment by camilasan** [comment]
ok, @k1l1, that sounds fine.
what do you think @juliushaertl ?

**Comment by camilasan** [comment]
thanks for the feedback @tabp0le 
I will revert the change here since this is turning out to be more complicated than I initially thought. Once we find a solution to it we put it back, ok @k1l1 ?

**Comment by k1l1** [comment]
@camilasan ok, from my side.
@tabp0le do you have some more information on that crash? The used Qt functions are pretty standard, so I am wondering why it would crash. Do you have special permissions on your appdata folder?

**Comment by camilasan** [comment]
I am jumping too quick on it. We merged the end to end encryption too so it could be anything :D
@tabp0le please, send the backtrace and which version of openssh you have (because of e2ee)

**Comment by tabp0le** [comment]
@camilasan 
**Compiled with:** OpenSSH_7.7p1, OpenSSL 1.1.0h  27 Mar 2018
https://pastebin.com/rmyZyhMJ

@k1l1 No special appdata permissions. Works fine on linux client, although the logging doesn't actually seem to work. (nothing shows up in the f12 log window)

**Comment by k1l1** [comment]
I possibly found the problem. http://agateau.com/2015/qdir-separator-considered-harmful/
I thought QDir::seperator would help preserve cross platform compatibility
```
const QString filename = foldername + QString(QDir::separator())  ///
+ folderPath.split(QString(QDir::separator())).at(length - 2) + QLatin1String("_sync.log");
```

This results in a broken link, a wrong pointer and end with a segmentation fault :(

**Comment by tabp0le** [comment]
@k1l1 guess it did the opposite of intended? :stuck_out_tongue: Hopefully that's the issue and we don't need to look any further.

**Comment by tabp0le** [comment]
@k1l1 Tested it, logging is working and no crashing on Windows! Thanks!

**Comment by camilasan** [comment]
@k1l1 does it also fix the conflict problem?

**Comment by k1l1** [comment]
Yes.

**Comment by camilasan** [comment]
Thanks @k1l1!

**Pull request merged**
