### PR TITLE
Merge upstream changes

### PR DESCRIPTION
**Pull request by rullzer**
Lets see if this breaks anything...

### CODE REVIEW

**Comment by juliushaertl** [comment]
@rullzer Seems like some icons need to be renamed: https://github.com/nextcloud/client/pull/135/commits/81c20352e1dfd7800f7c43ce8dc9bb08b68b33ce

**Comment by rullzer** [comment]
@juliushaertl yep noticed. Just pushed

**Comment by juliushaertl** [comment]
Pushed a commit to fix the libcloudproviders build (WITH_DBUS was removed by 257d8142b1af06e1a3892be5110b7b69e38a0659)

**Comment by rullzer** [comment]
I'll push a fix soonish to fix the AppImage build

**Comment by rullzer** [comment]
@camilasan could you also give this a test run?

**Pull request merged**
